
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author phia9
 */
public class AddStudent extends javax.swing.JFrame implements guiMethod {

    ArrayList<Professor> professorList;
    ArrayList<Student> studentList;
    ArrayList<Course> courseList;
    
    String selectedMajor = "CNIT";
    /**
     * Creates new form AddStudent
     */
    public AddStudent() {
        initComponents();
    }
    
    public AddStudent(ArrayList<Professor> list1, ArrayList<Student> list2, ArrayList<Course> list3) {
        professorList = list1;
        studentList = list2;
        courseList = list3;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Back = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Name = new javax.swing.JLabel();
        Age = new javax.swing.JLabel();
        NameText = new javax.swing.JFormattedTextField();
        Major = new javax.swing.JLabel();
        EnrollementDate = new javax.swing.JLabel();
        AgeText = new javax.swing.JFormattedTextField();
        EnrollmentDateText = new javax.swing.JFormattedTextField();
        jComboBox1 = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Name.setFont(new java.awt.Font("Bodoni MT Black", 1, 18)); // NOI18N
        Name.setText("Name:");

        Age.setFont(new java.awt.Font("Bodoni MT Black", 1, 18)); // NOI18N
        Age.setText("Age:");

        NameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextActionPerformed(evt);
            }
        });

        Major.setFont(new java.awt.Font("Bodoni MT Black", 1, 18)); // NOI18N
        Major.setText("Major:");

        EnrollementDate.setFont(new java.awt.Font("Bodoni MT Black", 1, 18)); // NOI18N
        EnrollementDate.setText("Enrollment Date: ");

        AgeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeTextActionPerformed(evt);
            }
        });

        EnrollmentDateText.setToolTipText("Dec.23.1998");
        EnrollmentDateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrollmentDateTextActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CNIT", "ENGR", "CS", "MATH", "CGT" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Save))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Major)
                                    .addComponent(EnrollementDate))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EnrollmentDateText)
                                    .addComponent(jComboBox1, 0, 312, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Name)
                                    .addComponent(Age))
                                .addGap(131, 131, 131)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(AgeText, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EnrollmentDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(EnrollementDate))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Back)
                            .addComponent(Save))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name)
                            .addComponent(NameText, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Age)
                            .addComponent(AgeText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Major)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        EnrollmentDateText.getAccessibleContext().setAccessibleDescription("Fall/Spring/Summer ####");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        openStudentPage();
    }//GEN-LAST:event_BackActionPerformed

    private boolean isInt(String a) {
        try {
            Integer.parseInt(a);
        } catch (Exception e) {
            return false;
        }
        return true;
    }
    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        
        if(NameText.getText().length() != 0 && AgeText.getText().length() != 0 && EnrollmentDateText.getText().length() != 0) {
            if(!isInt(AgeText.getText())) {
                JOptionPane.showMessageDialog(new javax.swing.JPanel(), "Please enter the correct age!");
            } else {
                int age = Integer.parseInt(AgeText.getText());
                String[] format = EnrollmentDateText.getText().toString().split(" ");

                if(format.length > 2) {
                    JOptionPane.showMessageDialog(new javax.swing.JPanel() , "3Please use \"Fall(Spring, Summer) 2020\" for the enrollment date");
                } else {
                    if(format[0].equals("Fall") || format[0].equals("Spring") || format[0].equals("Summer")) {
                        if (!isInt(format[1]) || format[1].length() != 4){
                            JOptionPane.showMessageDialog(new javax.swing.JPanel() , "2Please use \"Fall(Spring, Summer) 2020\" format for the enrollment date");
                        } else {
                            Student student = new Student(NameText.getText(), age, jComboBox1.getSelectedItem().toString(), EnrollmentDateText.getText());
                            studentList.add(student);
                            
                            openStudentPage();
                        }
                    } else {
                        JOptionPane.showMessageDialog(new javax.swing.JPanel() , "1Please use \"Fall(Spring, Summer) 2020\" for the enrollment date");
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(new javax.swing.JPanel() , "Please fill in all the blanks");
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void AgeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeTextActionPerformed

    private void NameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void EnrollmentDateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrollmentDateTextActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_EnrollmentDateTextActionPerformed

    private void openStudentPage(){
        this.dispose();
        openPage("StudentPage");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JFormattedTextField AgeText;
    private javax.swing.JButton Back;
    private javax.swing.JLabel EnrollementDate;
    private javax.swing.JFormattedTextField EnrollmentDateText;
    private javax.swing.JLabel Major;
    private javax.swing.JLabel Name;
    private javax.swing.JFormattedTextField NameText;
    private javax.swing.JButton Save;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void openPage(String name) {
        if(name.equals("StudentPage")){
            StudentPage StudentPage = new StudentPage(professorList, studentList, courseList);
            StudentPage.setVisible(true);
        }
    }
}
