
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author soomin
 */
public class ProfessorPage extends javax.swing.JFrame implements guiMethod{
    
    ArrayList<Professor> professorList;
    ArrayList<Student> studentList;
    ArrayList<Course> courseList;
    /**
     * Creates new form ProfessorPage
     */
    public ProfessorPage() {
        initComponents();
    }

    ProfessorPage(ArrayList<Professor> list1, ArrayList<Student> list2, ArrayList<Course> list3) {
        this.professorList = list1;
        this.studentList = list2;
        this.courseList = list3;
        
        initComponents();
        
        NameList.setModel(new DefaultListModel());

        
        DefaultListModel model = (DefaultListModel) NameList.getModel();

        if(professorList.size()!=0){
            for(int i = 0; i < professorList.size(); i++) {
                String data1 = "       " + professorList.get(i).getName() + "                                        " + professorList.get(i).getMajor();
                model.add(i,data1);
            }
        }
        
        NameList.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent evt) {
                JList list = (JList)evt.getSource();
                if (evt.getClickCount() == 2) {
                    // Double-click detected
                    int index = list.locationToIndex(evt.getPoint());
                    
                    //open details page by passing studentList.get(index)
                    openViewAddProfessor (professorList.get(index));
                    
                } else if (evt.getClickCount() == 3) {

                    // Triple-click detected
                    int index = list.locationToIndex(evt.getPoint());
                }
            }

        });
    }
    private void openViewAddProfessor(Professor prof) {
        ViewAddProfessor viewAddProfessor = new ViewAddProfessor(prof);
        viewAddProfessor.setVisible(true);
    }
        /*
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        Name = new javax.swing.JLabel();
        Major = new javax.swing.JLabel();
        AddProfessor = new javax.swing.JButton();
        NameList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        Name.setFont(new java.awt.Font("Bodoni MT Black", 1, 18)); // NOI18N
        Name.setText("Name ");

        Major.setFont(new java.awt.Font("Bodoni MT Black", 1, 18)); // NOI18N
        Major.setText("Major");

        AddProfessor.setText("Add Professor");
        AddProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddProfessorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Major)
                .addGap(275, 275, 275))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddProfessor)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(NameList, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddProfessor)
                    .addComponent(Back))
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(Major))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(NameList, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Back.getAccessibleContext().setAccessibleName("back");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        PurdueTime mainPage = new PurdueTime(professorList, studentList, courseList);
        mainPage.setVisible(true);
    }//GEN-LAST:event_BackActionPerformed

    private void AddProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProfessorActionPerformed
        // TODO add your handling code here:
        this.dispose();
        openPage("AddProfessorPage");
    }//GEN-LAST:event_AddProfessorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfessorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfessorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfessorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfessorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfessorPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddProfessor;
    private javax.swing.JButton Back;
    private javax.swing.JLabel Major;
    private javax.swing.JLabel Name;
    private javax.swing.JList<String> NameList;
    // End of variables declaration//GEN-END:variables

    @Override
    public void openPage(String name) {
        if(name.equals("AddProfessorPage")){
            AddProfessor AddProfessorPage = new AddProfessor(professorList, studentList, courseList);
            AddProfessorPage.setVisible(true);
        }
    }

}
